FROM python:3.8-slim
RUN pip install --no-cache-dir pandas numpy

WORKDIR /code
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

EXPOSE 5000
COPY . .
#CMD ["flask", "run"]
CMD ["python", "-m", "flask", "run"]